// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221026071422_CreateIdentity")]
    partial class CreateIdentity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CarService.Autoteenus", b =>
                {
                    b.Property<int>("AutoteenusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutoteenusID"), 1L, 1);

                    b.Property<int>("Aeg")
                        .HasColumnType("int");

                    b.Property<int>("Hind")
                        .HasColumnType("int");

                    b.Property<string>("autoteenus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AutoteenusID");

                    b.ToTable("Autoteenus");
                });

            modelBuilder.Entity("CarService.Klient", b =>
                {
                    b.Property<int>("KlientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KlientID"), 1L, 1);

                    b.Property<string>("Nimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vanus")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KlientID");

                    b.ToTable("Klient");
                });

            modelBuilder.Entity("CarService.Tellimus", b =>
                {
                    b.Property<int>("TellimusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TellimusID"), 1L, 1);

                    b.Property<DateTime>("Aeg")
                        .HasColumnType("datetime2");

                    b.Property<int>("AutoteenusID")
                        .HasColumnType("int");

                    b.Property<int>("KlientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Kuupaev")
                        .HasColumnType("datetime2");

                    b.Property<int>("TootajaID")
                        .HasColumnType("int");

                    b.HasKey("TellimusID");

                    b.HasIndex("AutoteenusID");

                    b.HasIndex("KlientID");

                    b.HasIndex("TootajaID");

                    b.ToTable("Tellimus");
                });

            modelBuilder.Entity("CarService.Tootaja", b =>
                {
                    b.Property<int>("TootajaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TootajaID"), 1L, 1);

                    b.Property<string>("Nimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefon")
                        .HasColumnType("int");

                    b.Property<int>("Vanus")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("haridus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TootajaID");

                    b.ToTable("Tootaja");
                });

            modelBuilder.Entity("CarService.Tellimus", b =>
                {
                    b.HasOne("CarService.Autoteenus", "Autoteenus")
                        .WithMany()
                        .HasForeignKey("AutoteenusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarService.Klient", "Klient")
                        .WithMany()
                        .HasForeignKey("KlientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarService.Tootaja", "Tootaja")
                        .WithMany()
                        .HasForeignKey("TootajaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autoteenus");

                    b.Navigation("Klient");

                    b.Navigation("Tootaja");
                });
#pragma warning restore 612, 618
        }
    }
}
